apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: codenameninja/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: codenameninja/container
      context: frontend/container
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
          - src: "public/**/*.html"
            dest: .
    - image: codenameninja/marketing
      context: frontend/marketing
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
          - src: "public/**/*.html"
            dest: .
    - image: codenameninja/client
      context: frontend/client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "components/**/*.js"
            dest: .
          - src: "pages/**/*.js"
            dest: .
          - src: "hooks/**/*.js"
            dest: .
    - image: codenameninja/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
